name: "Development"

on:
  push:
    branches:
      - "development"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
      RODA_OPTS: "RODA_CORE_SOLR_TYPE=CLOUD RODA_CORE_SOLR_CLOUD_URLS=localhost:2181"

    services:
      zookeeper:
        image: zookeeper:3.8
        ports:
          - 2181:2181
      solr:
        image: solr:9
        ports:
          - 8983:8983
        env:
          ZK_HOST: zookeeper:2181
        options: -e cloud

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Install dependencies
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20F802FE798E6857
          sudo add-apt-repository "deb https://www.itforarchivists.com/ buster main"
          sudo apt-get -qq update
          sudo apt-get -qq install siegfried -y
          sudo cp .github/workflows/bin/clamscan /usr/bin/clamscan
          sudo cp .github/workflows/bin/clamscan /usr/bin/clamdscan
          sudo chmod a+rx /usr/bin/clamscan /usr/bin/clamdscan
      - name: Run tests & install
        run:
          $RODA_OPTS mvn $MAVEN_CLI_OPTS -Dtestng.groups="travis" -Proda-wui-docker -Denforcer.skip=true clean org.jacoco:jacoco-maven-plugin:prepare-agent install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub packages
        run: mvn $MAVEN_CLI_OPTS clean deploy -Dmaven.test.skip=true -Pcore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deploy to DockerHub
        run: |
          docker tag keeps/roda:latest keeps/roda:development
          docker push keeps/roda:development
      - name: Trigger KEEPS GitLab CI/CD
        run: |
          curl --progress-bar -o /dev/null -L --request POST \
               --form ref=development \
               --form token=${{ secrets.GITLAB_RODA_DEV_TRIGGER_TOKEN }} \
               --form "variables[DOCKER_TAG]=development" \
               ${{ secrets.GITLAB_RODA_DEV_TRIGGER }}
