services:
  zoo1:
    image: zookeeper:3.8
    ports:
      - 2181:2181
    networks:
      - zoonet
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "3"
        compress: "true"

  solr1:
    image: solr:9
    networks:
      - zoonet
    ports:
      - "8983:8983"
    environment:
      ZK_HOST: zoo1:2181
    depends_on:
      - zoo1
    command:
      - -c
networks:
  zoonet: